version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tiendita?schema=public
      - JWT_SECRET=super-secret-jwt-key-change-in-production
      - JWT_EXPIRATION=1d
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tiendita
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
